# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arpit Bhayani | Geek at work
email: arpit.b.bhayani@gmail.com
description: I am a full stack developer, optimization freak, curious and a naive physics enthusiast. This is where I put my random thoughts and vague imaginations into words. You will also find solution to various competitive programming questions here.
baseurl: ""
url: "http://arpitbhayani.me"
img: http://arpitbhayani.me/static/images/arpit.jpg
keywords: blog, computer science, physics, competitive programming

permalink: /:categories/:title.html
highlighter: pygments
twitter_username: arpit_bhayani

# Build settings
markdown: kramdown
exclude: [static/semantic/src/, static/semantic/tasks, static/node_modules]
gems:
    - jekyll-sitemap
blog_types:
    - techie
    - curiosity
